### ISSUE TITLE
Hard to find the welcome page

### ISSUE THREAD

**Issue by matthewcurran** [atom/welcome#32]
I just downloaded Atom, and the welcome page was beautiful.  I sure wanted to read it.  But I closed Atom so I could move it from "downloads" to "desktop", and now I can't make the welcome page come back!

Searching for "welcome" in the help menu search bar gives zero results.

I also could not find a shortcut to re-open the welcome page by searching online.

Please consider adding a link to the welcome page to the "file", "view", or "help" menus.

**Comment by mnquintana** [comment]
It'll be in the Help menu in the next Atom release! (You can also find it by searching for `Welcome: Show` in the Command Palette with <kbd>Cmd / Ctrl - Shift - P</kbd>)

**Comment by matthewcurran** [comment]
Thank You!!!

**Comment by mnquintana** [comment]
Sorry about the delay on this – it'll actually be shipping in Atom 0.195.0!
