### ISSUE TITLE
Add stylesheet examples

### ISSUE THREAD

**Issue by oclbdk** [atom/welcome#34]
The Welcome Guide says there are stylesheet examples to uncomment

![screenshot 2015-05-19 14 39 50](https://cloud.githubusercontent.com/assets/136982/7710922/2cb584d4-fe35-11e4-95ee-0970731910ce.png)

However, the stylesheet is empty:

![screenshot 2015-05-19 14 40 01](https://cloud.githubusercontent.com/assets/136982/7710941/6101c1bc-fe35-11e4-93da-4fec62e1efcf.png)

**Comment by 50Wliu** [comment]
`styles.less` in the Atom repo definitely isn't empty: https://github.com/atom/atom/blob/master/dot-atom/styles.less
This bug is still valid though since there aren't any examples to uncomment.
