### ISSUE TITLE
Cannot scroll back up after expanding sections in the Welcome Guide

### ISSUE THREAD

**Issue by amytruong** [atom/welcome#44]
Installed a fresh copy of Atom and when in the Welcome Guide, if I expand a section, I cannot scroll back up in the app. 

**Steps to reproduce:**
1. Open up Atom (in regular or safe mode) 
2. Help --> Welcome Guide 
3. Expand "Open a Project"
4. Expand "Install a Package"
5. Scroll back up and down 

**Expected Results:** The app quickly and smoothly scrolls back up
**Actual Results:** I can't scroll back up and the sections are "cut off"

![welcome](https://cloud.githubusercontent.com/assets/10725993/11345786/37eeef6e-9211-11e5-9aa8-777318a531ec.gif)
![screen shot 2015-11-23 at 6 00 07 pm](https://cloud.githubusercontent.com/assets/10725993/11345789/3ad302a6-9211-11e5-9651-a6aa13757772.png)

**Atom version:** Verison 1.2.3
**OS and version:** Windows 8.1 on VMWare Fusion Professional 7.3.1

**Installed packages:** Zero

**Additional information:**
* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: Yes - wasn't happening for me before.
* Problem can be reliably reproduced, doesn't happen randomly: For me, yes
* Problem happens with all files and projects, not only some files or projects: n/a

**Comment by benogle** [comment]
I think this was fixed in #43

**Comment by amytruong** [comment]
@benogle thanks ben! sorry. ran the issue by with @izuzak and it looks like we both missed it! closing now :smile:
