### ISSUE TITLE
The guide points to a non-existent menu in Windows and Linux

### ISSUE THREAD

**Issue by robbertvs** [atom/welcome#46]
The guide contains the following lines:
<strong>Next time:</strong> You can open your stylesheet from Menu > Atom.
<strong>Next time:</strong> You can open your init script from Menu > Atom.
<strong>Next time:</strong> You can open your snippets in Menu > Atom.

This points to the darwin.cson menu file here: https://github.com/atom/atom/tree/master/menus.
The menus for Windows and Linux however have this menu item placed in Menu > File. The guide should be changed according to the platform.

**Comment by robbertvs** [comment]
Could I work on this issue myself? It would be my first contribution to the Atom project.

**Comment by 50Wliu** [comment]
> Could I work on this issue myself?

Of course!
