### ISSUE TITLE
Checkbox label doesn't have `for` attribute.

### ISSUE THREAD

**Issue by dsandstrom** [atom/welcome#63]
Makes user click checkbox instead of allowing the label to be clicked.  Weird part is I see the attribute in the code (https://github.com/atom/welcome/blob/7d94660a35b94487242705c9241748a4c52191b6/lib/welcome-view.js#L73), but not in the dom.

![2017-06-12_1031](https://user-images.githubusercontent.com/1400414/27047040-8499126e-4f5b-11e7-85a8-b3a6ed39b0a8.png)

Atom 1.17.2, Welcome 0.36.3

**Comment by simurai** [comment]
The `for` is actually [there](https://github.com/atom/welcome/blob/9850c793418b5165549cc47e3fad8edaa4adb3b2/lib/welcome-view.js#L73) too, but somehow gets stripped when rendering? 🤔 

Anyways, there is now a PR #64 that just wraps the input.
